### ISSUE TITLE
Source CourseInfo data

### ISSUE THREAD

**Issue by tim-macphail** [techstartucalgary/lifeline#198]
Is hardcoded https://github.com/techstartucalgary/lifeline/blob/665534de775f09352a2c62bac0a7409c6119cd2d/client/src/pages/Review/CoursePanel.tsx#L33
Not sure where we're actually sourcing the data, I assumed Yunfan had a plan for this

**Comment by cloudyyoung** [comment]
This was already done in https://github.com/techstartucalgary/lifeline/pull/100, in the backend. The response body for uploading syllabus has already containing information like this:
<img width="856" alt="Screenshot 2023-02-28 at 11 19 23 PM" src="https://user-images.githubusercontent.com/20573623/222060324-76649f2c-a960-4042-b6bf-9c610bfe6cbb.png">

Frontend could just read them from response body like `res.data.hours` or `res.data.prereq`.


----

In #100 things are stored in `jsonlines` files because I asked and we didn't plan for using a database. Now since we are using MongoDB so it's better to do https://github.com/techstartucalgary/lifeline/issues/195, migrate them to database.

**Comment by tim-macphail** [comment]
> This was already done in #100, in the backend. The response body for uploading syllabus has already containing information like this: <img alt="Screenshot 2023-02-28 at 11 19 23 PM" width="856" src="https://user-images.githubusercontent.com/20573623/222060324-76649f2c-a960-4042-b6bf-9c610bfe6cbb.png">
> 
> Frontend could just read them from response body like `res.data.hours` or `res.data.prereq`.
> 
> In #100 things are stored in `jsonlines` files because I asked and we didn't plan for using a database. Now since we are using MongoDB so it's better to do #195, migrate them to database.

Oh ok, I wasn't sure if `description` was what we needed. Should be easy then. I'll wait until #201 is in since it modifies how the response is processed.
