### ISSUE TITLE
PDF viewer bugs and issues

### ISSUE THREAD

**Issue by cloudyyoung** [techstartucalgary/lifeline#232]
This issue contains all the bugs and issues found to be introduced in #226.

### 1. As mentioned in the PR comment, the following snippet in the `src/index.ts` should not be removed.

```
  -moz-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
  user-select: none;
```

Since the project is a **single web app** on desktop and eventually a **progressive web app** on mobile, to emphasize the concept of **app** is important for such project. There are different gestures introduced to the user interface, and being able to select texts across the whole page is not a good user experience (by intention or by accident).

<img src="https://user-images.githubusercontent.com/20573623/224423388-335ca0b4-3c8e-4d51-a98c-d1e1c070f7bc.PNG" width="200" />
  
Some areas might be designed to be able to let users select texts, in this case, should apply `user-select: text` style on **the specific container** of selectable texts.

### 2. Data persistence is not working for PDF.

It's always showing "Loading PDF..."

<img width="800" alt="Screenshot 2023-03-10 at 1 39 52 PM" src="https://user-images.githubusercontent.com/20573623/224424012-a02a70fc-1262-4dff-974f-3f01e1c146d7.png">

### 3. Nested scrolling panel. 

This is also bad user experience for all screens, especially mobile screen. 

<img width="700" alt="Screenshot 2023-03-10 at 1 49 09 PM" src="https://user-images.githubusercontent.com/20573623/224425494-b6908ae8-5ca5-4746-8864-d0ec172bfb40.png">

<img width="345" alt="Screenshot 2023-03-10 at 1 42 28 PM" src="https://user-images.githubusercontent.com/20573623/224424431-6d2111b5-5297-4ec8-80e4-abcb18cb43ea.png">

PDF viewer is not a nested scrollable container but a regular flow content and has relatively positioned assessment card associated to it. Please refer to _THE website_ and check out the implementation.

I have also created this prototype to showcase the desired final result: https://www.figma.com/proto/IVhWdzrln3zC3MRo63mkW9/Prototype-v3.0?page-id=84%3A3916&node-id=84%3A3917&viewport=-4659%2C300%2C0.37&scaling=scale-down&starting-point-node-id=84%3A3917

A video version of it:

https://user-images.githubusercontent.com/20573623/224435915-d31462d7-5acd-4bd8-89f3-d74bc0645f85.mov

**Comment by tim-macphail** [comment]
Oops I just yolo merged it because I was getting impatient with it not being there... 
1. For the text highlighting, I had previously (I forget if on discord or github) asked to keep text selection on. I think we should have it by default on, and disable it for things we don't want highlighted. Personally when I use websites, I'm always highlighting text and not being able to do it is quite annoying.
2. I was aware of the data persistence and made an issue for it in #227 
3. I'm still confused on what the behaviour should be exactly based on the prototype, but the pdf viewer should be able to scroll independently from the assessments, a) for the use to manually look around and b) it will auto-scroll to the source of an deadline when the assessment is clicked as required in #229
